name: pymol_paratope_heatmap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy>=2.0
  - pyyaml
  - pyqt
  - python=3.10
  - glew
  - libpng
  - libnetcdf
  - freetype
  - glm
  - biopython
